//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ice.Project.Config {


  public class MountTemplate : IGeneratorObject {

    // 索引
    public int Id { get; private set; }

    public void Read(ConfigElement element) {
      this.Id = GeneratorUtility.Get(element, "Id", this.Id);
      this.OnInit();
    }

    protected virtual void OnInit() {
    }

    public static MountTemplate[] Load() {
      return Load<MountTemplate>();
    }

    public static T[] Load<T>()
        where T : MountTemplate, new() {
      return GeneratorUtility.Load<T>("MountsConfig", "Mount");
    }
  }
}
